[build]
  command = "npx quartz build && npx pagefind --site public --output-subdir _pagefind --root-selector \"article.popover-hint\""
  publish = "public"

[build.environment]
  NODE_OPTIONS = "--max-old-space-size=8192"
